name: grpc-example
version: "3.7"

networks:
  app:
    driver: bridge

services:
  nginx-gateway:
    image: nginx
    container_name: api-gateway
    ports:
      - "8000:80"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - app

  chat_service:
    build:
      context: .
      dockerfile: chat-service/Dockerfile
      tags:
        - "chat-service:v1"
    container_name: chat_service
    ports:
      - "9001:9091"
    networks:
      - app  
      
  user_service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
      tags:
        - "user-service:v1"
    container_name: user_service
    ports:
      - "9000:9090"
    networks:
      - app
        
  message_service:
    build:
      context: .
      dockerfile: message-service/Dockerfile
      tags:
        - "message-service:v1"
    container_name: message_service
    ports:
      - "9002:9092"
    networks:
      - app

